sources/cargo.py: Fix alias
URLs need to be "marked". The plugin marked the base URL instead of
the URLs of the crates. This broke an assertion:

```
          File "/home/user/.local/lib/python3.7/site-packages/bst_external/sources/cargo.py", line 246, in _get_url
            alias_override=alias)
          File "/home/user/.local/lib/python3.7/site-packages/buildstream/source.py", line 547, in translate_url
            self.mark_download_url(url, primary=primary)
          File "/home/user/.local/lib/python3.7/site-packages/buildstream/source.py", line 615, in mark_download_url
            "URL was not seen at configure time: {}".format(url)
        AssertionError: URL was not seen at configure time: tar_https:static.crates.io/crates
```